services:
  - type: web
    name: mbti-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server-new.js
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyDGdD03lj8HBwed5htBNzTSK0Tz3JRoaMg
      - key: NODE_ENV
        value: production